openapi: 3.0.0
info:
  title: DART 기업 공시 API
  description: 기업명을 통해 고유 코드를 조회하고, 해당 기업의 최근 공시 정보를 확인할 수 있는 API입니다.
  version: 1.0.0
servers:
  - url: https://jasonkim2580.github.io/dart-api-gpt  # 실제 API 서버 주소로 대체 필요 (FastAPI 실행 주소 또는 이후 호스팅 주소)

paths:
  /get_corp_code:
    get:
      summary: 기업명으로 고유코드 리스트 조회
      parameters:
        - in: query
          name: company_name
          schema:
            type: string
          required: true
          description: 기업명 일부 또는 전체
      responses:
        '200':
          description: 검색된 기업 리스트 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    items:
                      type: object
                      properties:
                        corp_name:
                          type: string
                        corp_code:
                          type: string

  /get_reports:
    get:
      summary: 고유코드로 최근 공시 10건 조회
      parameters:
        - in: query
          name: corp_code
          schema:
            type: string
          required: true
          description: DART 고유 기업 코드
      responses:
        '200':
          description: 최근 공시 목록 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  reports:
                    type: array
                    items:
                      type: object
                      properties:
                        report_date:
                          type: string
                        report_name:
                          type: string
                        receipt_no:
                          type: string
